name: Lint

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    name: Lint X5 Bridge
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v7.0.0

      - name: Run Home Assistant app linter
        uses: frenck/action-addon-linter@v2.21
        with:
          path: "./x5_bridge"
